# Generated by Django 5.1.2 on 2024-10-16 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_user_post_author_post_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='orientation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
