# Generated by Django 5.1.2 on 2024-10-28 15:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_post_view_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('image_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='post_images')),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.post')),
            ],
        ),
    ]
