# Generated by Django 5.1.2 on 2024-10-29 08:43

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_postimage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='highest_offer_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=15),
        ),
        migrations.CreateModel(
            name='Negotiation',
            fields=[
                ('negotiation_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('offer_price', models.DecimalField(decimal_places=1, max_digits=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='negotiations', to='application.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
