# Generated by Django 5.1.2 on 2024-10-29 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_post_highest_offer_price_negotiation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='highest_offer_price',
        ),
    ]
