# Generated by Django 5.1.2 on 2024-10-29 09:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0008_delete_negotiation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='sale_status',
            field=models.CharField(choices=[('đang bán', 'Đang bán'), ('đang thương lượng', 'Đang thương lượng'), ('đã cọc', 'Đã cọc'), ('đã bán', 'Đã bán')], default='đang bán', max_length=20),
        ),
        migrations.CreateModel(
            name='Negotiation',
            fields=[
                ('negotiation_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('offer_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_accepted', models.BooleanField(default=False)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='negotiations', to='application.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('post', 'user')},
            },
        ),
    ]
