# Generated by Django 5.1.2 on 2024-11-02 11:05

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0009_alter_post_sale_status_negotiation'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='highest_offer_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=15, null=True),
        ),
    ]
