# Generated by Django 5.1.2 on 2024-11-04 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0013_remove_negotiation_highest_offer_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='highest_offer_user',
        ),
    ]
