# Generated by Django 5.1.2 on 2024-11-16 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0016_post_save_count_savedpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=30, null=True),
        ),
    ]
