# Generated by Django 5.1.2 on 2024-11-22 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0017_post_latitude_post_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='land_lot',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='land_parcel',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='map_sheet_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='ward',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
