# Generated by Django 5.1.2 on 2024-11-22 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0018_post_land_lot_post_land_parcel_post_map_sheet_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='price',
            field=models.BigIntegerField(),
        ),
    ]
