# Generated by Django 5.1.2 on 2024-11-23 16:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0019_alter_post_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='negotiation',
            name='offer_price',
        ),
        migrations.RemoveField(
            model_name='post',
            name='highest_offer_price',
        ),
        migrations.RemoveField(
            model_name='post',
            name='highest_offer_user',
        ),
        migrations.AddField(
            model_name='negotiation',
            name='is_considered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='negotiation',
            name='negotiation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='negotiation',
            name='negotiation_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='negotiation',
            name='negotiation_price',
            field=models.BigIntegerField(default=1000000000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='negotiation',
            name='payment_method',
            field=models.CharField(default='khác', max_length=50, verbose_name=[('một lần', 'Một lần'), ('trả góp', 'Trả góp'), ('trả trước', 'Trả trước'), ('khác', 'Khác')]),
        ),
        migrations.AddField(
            model_name='post',
            name='highest_negotiation_price',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='highest_negotiation_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='highest_negotiation_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='legal_status',
            field=models.CharField(choices=[('sổ đỏ/sổ hồng', 'Sổ đỏ/Sổ hồng'), ('chưa có', 'Chưa có'), ('khác', 'Khác')], max_length=50),
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('proposal_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('proposal_price', models.BigIntegerField(blank=True, null=True)),
                ('proposal_date', models.DateField(blank=True, null=True)),
                ('proposal_method', models.CharField(blank=True, max_length=255, null=True)),
                ('proposal_note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('negotiation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='application.negotiation')),
            ],
        ),
    ]
