# Generated by Django 5.1.2 on 2024-11-23 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0020_remove_negotiation_offer_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proposal',
            old_name='created_by',
            new_name='user',
        ),
    ]
