# Generated by Django 5.1.2 on 2024-11-24 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0021_rename_created_by_proposal_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
