# Generated by Django 5.1.2 on 2024-11-24 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0018_report'),
        ('application', '0022_proposal_is_accepted'),
    ]

    operations = [
    ]
