# Generated by Django 5.1.2 on 2024-11-25 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0022_proposal_is_accepted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='proposal_method',
            field=models.CharField(default='khác', max_length=50, verbose_name=[('một lần', 'Một lần'), ('trả góp', 'Trả góp'), ('trả trước', 'Trả trước'), ('khác', 'Khác')]),
        ),
    ]
