# Generated by Django 5.1.2 on 2024-11-25 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0023_merge_0018_report_0022_proposal_is_accepted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_type',
            field=models.CharField(choices=[('post', 'Bài đăng'), ('comment', 'Bình luận'), ('user', 'Người dùng')], max_length=50),
        ),
    ]
