# Generated by Django 5.1.2 on 2024-11-25 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0023_alter_proposal_proposal_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='length',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='width',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=20, null=True),
        ),
    ]
