# Generated by Django 5.1.2 on 2024-11-27 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0024_post_length_post_width'),
    ]

    operations = [
        migrations.AddField(
            model_name='negotiation',
            name='average_response_time',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
