# Generated by Django 5.1.2 on 2024-11-26 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0024_alter_report_description_alter_report_report_type'),
        ('application', '0024_post_length_post_width'),
    ]

    operations = [
    ]
