# Generated by Django 5.1.2 on 2024-11-27 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0023_merge_0018_report_0022_proposal_is_accepted'),
        ('application', '0025_negotiation_average_response_time'),
    ]

    operations = [
    ]
