# Generated by Django 5.1.2 on 2024-11-27 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0026_merge_20241128_0213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_type',
            field=models.CharField(choices=[('post', 'Bài đăng'), ('comment', 'Bình luận'), ('user', 'Người dùng')], max_length=50),
        ),
    ]
