# Generated by Django 5.1.2 on 2024-12-05 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0027_alter_report_description_alter_report_report_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcomment',
            name='is_report_removed',
            field=models.BooleanField(default=False),
        ),
    ]
