# Generated by Django 5.1.2 on 2024-12-01 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0025_merge_20241126_1124'),
        ('application', '0027_alter_report_description_alter_report_report_type'),
    ]

    operations = [
    ]
