# Generated by Django 5.1.2 on 2024-12-07 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0028_merge_20241201_1028'),
        ('application', '0028_postcomment_is_report_removed'),
    ]

    operations = [
    ]
