# Generated by Django 5.1.2 on 2024-11-23 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0020_remove_negotiation_offer_price_and_more'),
        ('chatting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='negotiation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chatrooms', to='application.negotiation'),
        ),
    ]
