name: Django CI/CD

on:
  push:
    branches:
      - deploy
  pull_request:
    branches:
      - deploy

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' 

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt

      # - name: Run tests
      #   working-directory: backend
      #   run: |
      #     python manage.py test


  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: SSH to server and deploy
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd pbl6
          cd PBL6-RealEstateBrokerageSystem
          git checkout deploy
          git pull origin deploy
          cd backend
          source env/bin/activate
          pip install -r requirements.txt
          python manage.py migrate
          python manage.py collectstatic
          sudo systemctl daemon-reload
          sudo systemctl restart gunicorn.service
          sudo systemctl restart nginx